import 'dart:convert';
import 'package:intl/intl.dart';
import 'package:url_launcher/url_launcher.dart';
import '../models/sale_entry.dart';

class ExportService {
  /// Generates a beautifully formatted summary for WhatsApp / SMS sharing
  static String generateSummaryText(
    List<SaleEntry> sales,
    double total,
    DateTime date,
  ) {
    final dateStr = DateFormat('dd/MM/yyyy').format(date);
    final buffer = StringBuffer();
    buffer.writeln('🧾 *VoiceBill Daily Sales Report*');
    buffer.writeln('📅 Date: $dateStr');
    buffer.writeln('------------------------------');

    if (sales.isEmpty) {
      buffer.writeln('No sales recorded today.');
    } else {
      final itemCounts = <String, double>{};
      final itemTotals = <String, double>{};

      for (final s in sales) {
        final name = '${s.item[0].toUpperCase()}${s.item.substring(1)}';
        itemCounts[name] = (itemCounts[name] ?? 0) + s.quantity;
        itemTotals[name] = (itemTotals[name] ?? 0) + s.total;
      }

      for (final entry in itemCounts.entries) {
        final qty = _fmt(entry.value);
        final itemTotal = _fmt(itemTotals[entry.key]!);
        buffer.writeln('• ${entry.key} - $qty unit(s) = ₹$itemTotal');
      }
    }

    buffer.writeln('------------------------------');
    buffer.writeln('💰 *TOTAL COLLECTION: ₹${_fmt(total)}*');
    buffer.writeln('📊 Total Orders: ${sales.length}');
    buffer.writeln('\nGenerated by VoiceBill 🎙️');
    return buffer.toString();
  }

  /// Opens WhatsApp with the daily report pre-filled
  static Future<bool> shareOnWhatsApp(String text) async {
    final encodedText = Uri.encodeComponent(text);
    final url = Uri.parse('https://wa.me/?text=$encodedText');
    if (await canLaunchUrl(url)) {
      return launchUrl(url, mode: LaunchMode.externalApplication);
    }
    return false;
  }

  /// Generates a CSV spreadsheet and opens it for download
  static Future<bool> downloadCsv(
    List<SaleEntry> sales,
    double total,
    DateTime date,
  ) async {
    final buffer = StringBuffer();
    buffer.writeln('ID,Item,Quantity,PricePerUnit(INR),Total(INR),Time,Confidence');

    for (final s in sales) {
      final timeStr = DateFormat('hh:mm a').format(s.timestamp);
      final item = s.item.replaceAll(',', ' ');
      buffer.writeln(
        '${s.id},$item,${_fmt(s.quantity)},${_fmt(s.pricePerUnit)},${_fmt(s.total)},$timeStr,${s.confidence.toStringAsFixed(2)}',
      );
    }

    buffer.writeln('TOTAL,,,,${_fmt(total)},,');

    final csvContent = buffer.toString();
    final bytes = utf8.encode(csvContent);
    final base64Csv = base64Encode(bytes);
    final dataUrl = Uri.parse('data:text/csv;base64,$base64Csv');

    if (await canLaunchUrl(dataUrl)) {
      return launchUrl(dataUrl, mode: LaunchMode.platformDefault);
    }
    return false;
  }

  static String _fmt(double v) =>
      v == v.roundToDouble() ? v.toStringAsFixed(0) : v.toStringAsFixed(2);
}
